# Generated by Django 4.2.21 on 2025-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="target_number",
            field=models.IntegerField(default=0),
        ),
    ]
