# Generated by Django 4.2.21 on 2025-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0002_game_is_active_game_target_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="game",
            name="target_number",
        ),
        migrations.AddField(
            model_name="game",
            name="board",
            field=models.JSONField(default=list),
        ),
    ]
