# Generated by Django 4.2.21 on 2025-05-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_remove_game_is_active_remove_game_target_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pieces_in_hand',
            field=models.JSONField(default=dict),
        ),
    ]
