# Generated by Django 4.2.21 on 2025-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_game_pieces_in_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='depth',
            field=models.IntegerField(default=0),
        ),
    ]
